# Generated by Django 2.2.28 on 2022-08-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_gitlabrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffusionrepo',
            name='gitlab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffusion', to='tools.GitlabRepo'),
        ),
        migrations.AddField(
            model_name='diffusionrepo',
            name='is_mirror',
            field=models.BooleanField(default=False),
        ),
    ]
