# Generated by Django 2.2.28 on 2024-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labsauth", "0002_ldapuser_posixaccount_posixgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labsuser",
            name="ldapemail",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="Developer account email address",
            ),
        ),
        migrations.AlterField(
            model_name="labsuser",
            name="ldapname",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Developer account username"
            ),
        ),
    ]
