# Generated by Django 2.2.28 on 2024-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labsauth", "0003_update_ldap_label_to_developer_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="labsuser",
            name="sulid",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="SUL user ID"
            ),
        ),
    ]
