# Generated by Django 4.2.21 on 2025-06-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labsauth", "0004_labsuser_sulid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labsuser",
            name="realname",
        ),
    ]
