# SPDX-License-Identifier: Apache-2.0

# Keystone policy exceptions
#
#  This file attempts to only include rules that differ from
#  upstream defaults.  To view the complete set of default rules
#  on a cloudcontrol node, run
#
#   oslopolicy-sample-generator --namespace keystone
#
#  To detect redundant rules in our custom config on a cloudcontrol,
#  run
#
#   oslopolicy-list-redundant --namespace keystone
#

#  Many of these rule definitions will be judged redundant by
#  oslopolicy-list-redundant but they're included to provide
#  context for the policies that follow
member_role: role:member
keystonevalidate_role: role:keystonevalidate

# We basically never want to give rights to mere project members, only
#  project admins.  So, replace this (upstream) rule with the admin_or_owner
#  rule below
# admin_or_owner: is_admin:True or project_id:%(project_id)s
admin_or_owner: is_admin:True or rule:member_role

#  There are a few reasons why we override default policies:
#
#   - permissive policies ('') to allow the nova_observer user
#     to read things
#
#   - restrictive and member policies to distinguish between
#     a project member and a project admin (these aren't present in
#     keystone but are used elsewhere)
#
#   - restrictive admin-only policies that disable features we don't
#     use in wmcs
#

# keystone can't change passwords, it regards ldap as read-only.
identity:update_user: "!"

identity:get_domain: ""
identity:get_domain_config: ""
identity:get_domain_config_default: ""
identity:get_domain_role: ""
identity:get_role: ""
identity:get_role_for_trust: ""
identity:get_service: ""
identity:get_user: ""
identity:get_project: ""
identity:list_domains: ""
identity:list_domains_for_user: ""
identity:list_endpoints: ""
identity:list_groups: ""
identity:list_projects: ""
identity:list_projects_for_user: ""
identity:list_revoke_events: ""
identity:list_role_assignments: ""
identity:list_roles: ""
identity:list_roles_for_trust: ""
identity:list_services: ""
identity:list_user_projects: ""
identity:list_users: ""

identity:validate_token: rule:admin_required or (role:reader and system_scope:all)
  or rule:service_role or rule:token_subject or rule:keystonevalidate_role

# These are custom rules added by WMF to manage the member
#  panel in Horizon
members:grant_membership: rule:admin_or_owner
members:revoke_membership: rule:admin_or_owner
members:toggle_member: rule:admin_or_owner
