# Keystone policy exceptions
#
#  This file attempts to only include rules that differ from
#  upstream defaults.  To view the complete set of default rules
#  on a cloudcontrol node, run
#
#   oslopolicy-sample-generator --namespace keystone
#
#  To detect redundant rules in our custom config on a cloudcontrol,
#  run
#
#   oslopolicy-list-redundant --namespace keystone
#


#  Many of these rule definitions will be judged redundant by
#  oslopolicy-list-redundant but they're included to provide
#  context for the policies that follow
admin_required: role:admin or is_admin:1
service_or_admin: rule:admin_required or rule:service_role
service_role: role:service
projectadmin_role: role:projectadmin
admin_or_projectadmin: rule:admin_required or rule:projectadmin_role
default: rule:admin_or_projectadmin


#  There are a few reasons why we override default policies:
#
#   - permissive policies ('') to allow the nova_observer user
#     to read things
#
#   - restrictive and projectadmin policies to distinguish between
#     a project member and a project admin (these aren't present in
#     keystone but are used elsewhere)
#
#   - restrictive admin-only policies that disable features we don't
#     use in wmcs
#

# keystone can't change passwords, it regards ldap as read-only.
identity:change_password: null


identity:get_domain: rule:admin_required
identity:get_identity_provider: rule:admin_required
identity:get_project: rule:admin_required
identity:get_role: ''
identity:get_role_for_trust: ''
identity:get_service: ''
identity:get_user: ''
identity:list_domains_for_groups: ''
identity:list_endpoints: ''
identity:list_projects: ''
identity:list_projects_for_groups: ''
identity:list_revoke_events: ''
identity:list_role_assignments: ''
identity:list_roles: ''
identity:list_roles_for_trust: ''
identity:list_services: ''
identity:list_trusts: rule:admin_required
identity:list_user_projects: ''
identity:list_users: ''
identity:validate_token_head: rule:service_or_admin

# These are custom rules added by WMF to manage the member
#  panel in Horizon
members:grant_membership: rule:admin_or_projectadmin
members:revoke_membership: rule:admin_or_projectadmin
members:toggle_projectadmin: rule:admin_or_projectadmin
